pref("extensions.abprime.currentVersion", "0.0");
pref("extensions.abprime.enabled", true);
pref("extensions.abprime.frameobjects", false);
pref("extensions.abprime.fastcollapse", false);
pref("extensions.abprime.showinstatusbar", false);
pref("extensions.abprime.detachsidebar", false);
pref("extensions.abprime.defaulttoolbaraction", 0);
pref("extensions.abprime.defaultstatusbaraction", 0);
pref("extensions.abprime.sidebar_key", "Accel Shift V, Accel Shift U");
pref("extensions.abprime.sendReport_key", "");
pref("extensions.abprime.filters_key", "Accel Shift E, Accel Shift F, Accel Shift O");
pref("extensions.abprime.enable_key", "");
pref("extensions.abprime.flash_scrolltoitem", false);
pref("extensions.abprime.previewimages", true);
pref("extensions.abprime.data_directory", "adblockplus");
pref("extensions.abprime.patternsbackups", 0);
pref("extensions.abprime.patternsbackupinterval", 0);
pref("extensions.abprime.whitelistschemes", "about chrome irc moz-safe-about news resource snews x-jsd addbook cid imap mailbox nntp pop data javascript moz-icon");
pref("extensions.abprime.hideimagemanager", true);
pref("extensions.abprime.subscriptions_autoupdate", false);
pref("extensions.abprime.subscriptions_listurl", "");
pref("extensions.abprime.subscriptions_fallbackurl", "");
pref("extensions.abprime.subscriptions_fallbackerrors", 0);
pref("extensions.abprime.documentation_link", "");
pref("extensions.abprime.savestats", false);
pref("extensions.abprime.composer_default", 2);
pref("extensions.abprime.clearStatsOnHistoryPurge", false);
pref("extensions.abprime.report_submiturl", "");
pref("extensions.abprime.recentReports", "");
pref("services.sync.engine.abprime", false);